### ISSUE TITLE
Configuration for rule "indent" is invalid

### ISSUE THREAD

**Issue by bherila** [continuationlabs/eslint-config-hapi#2]
```
Benjamins-MacBook-Pro:bell ben$ npm install -g eslint-config-hapi eslint-plugin-hapi
eslint-config-hapi@2.0.0 /usr/local/lib/node_modules/eslint-config-hapi

eslint-plugin-hapi@1.2.0 /usr/local/lib/node_modules/eslint-plugin-hapi
├── hapi-scope-start@1.1.2
├── hapi-capitalize-modules@1.1.1
└── no-shadow-relaxed@1.0.1 (eslint@0.24.1)
Benjamins-MacBook-Pro:bell ben$ eslint .
/usr/local/lib/node_modules/eslint/lib/config.js:129
                    throw e;
                          ^
Error: eslint-config-hapi:
	Configuration for rule "indent" is invalid:
	Value "data["2"].SwitchCase" has additional properties.

Referenced from: /Users/ben/projects/bell/node_modules/lab/lib/linters/eslint/.eslintrc
Referenced from: /Users/ben/projects/bell/.eslintrc
    at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/config-validator.js:88:15)
    at /usr/local/lib/node_modules/eslint/lib/config-validator.js:101:13
    at Array.forEach (native)
    at Object.validate (/usr/local/lib/node_modules/eslint/lib/config-validator.js:100:35)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:99:19)
    at /usr/local/lib/node_modules/eslint/lib/config.js:123:46
    at Array.reduceRight (native)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:111:36)
    at /usr/local/lib/node_modules/eslint/lib/config.js:123:46
    at Array.reduceRight (native)
```

**Comment by cjihrig** [comment]
You need ESLint 1.x.x to support proper linting of switch-case. Or, you can use eslint-config-hapi < 2.0.0.
